[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 10
clear_on_start = false
tx_confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'NAMADA_CHAIN_ID'  # set your chain ID
memo_prefix = 'MEMO_PRIFIX'
type = 'Namada'
rpc_addr = 'http://127.0.0.1:26657'  # set the IP and the port of the chain
grpc_addr = 'http://127.0.0.1:9090'  # not used for now
event_source = { mode = 'push', url = 'ws://127.0.0.1:26657/websocket', batch_delay = '500ms' }  # set the IP and the port of the chain

trusting_period = 'NAMADA_TRUSTING_PERIOD'
rpc_timeout = '30s'

account_prefix = ''  # not used
key_name = 'NAMADA_RELAYER'  # The key is an account name you made
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'NAMADA_DENOM' }  # the price isn't used for now, the denom should be a raw token address

[[chains]]
id = 'osmo-test-5'
memo_prefix = 'MEMO_PRIFIX'
type = "CosmosSdk"

rpc_addr = 'http://127.0.0.1:OSMO_RPC_PORT'
grpc_addr = 'http://127.0.0.1:OSMO_GRPC_PORT'
event_source = { mode = 'push', url = 'ws://127.0.0.1:OSMO_RPC_PORT/websocket', batch_delay = '500ms' }

rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'

default_gas = 400000
max_gas = 120000000
gas_price = { price = 0.01, denom = 'uosmo' }
gas_multiplier = 1.1

max_msg_num = 30
max_tx_size = 1800000
clock_drift = '300s'
max_block_time = '30s'
trusting_period = '288000s'
trust_threshold = { numerator = '1', denominator = '3' }
